apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: !!
  labels:
    app: wordpress
spec:
  # Se a linha abaixo nao existir, o kubernetes vai escolher o storageclass default
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi